# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lV2998LrCwmss4AbgSN3Vy+MtAbeFTqB/fnmgKlWjcxByfWU55XT7FEoBgMauwPWjzRB3bhVRjHxj+ENy+qSJysn1/HxRSFnzUuqXYwUm6s+AhCeDEaf0RINldEdTudCWXyfBakf59WUI/4GukGNaxTkT7RtAIJjG+5vNk2djTPHzUDbQjqv2PDqO8uIXdqWYJdYLITuPO+jMGWIAV9RTfIjb2soZP5LY/phpMjt4RAW1X5sJiGJuXENjB7cjQkwB6bxMrRjA1pF38wrMFPQZXr6z/aietQ93puw9rl8ubenorC8iQu0OZsj2EXnbbL0910rQn+HHC8d8vU+rCAKzK0o22tjquB9OEs5Y8IYmxo6KACUq4KHcArsR2l+lZHat+d8vF1e1XMKX88VEoV45zHISevtd7foqXhwo6Pg0oYeR1yJWaj3mTa3lcv+2rwjIDrdW3wWb06SDgOZCW1wjcCaoOG0kPdtIfB7aZRRxwSyXiJLL5HqsJLNF2ocjJLvEsHb8P9/p764XEG/qOux4S3HQEoi/5cFylf15jThzmUfh5yrYyQqEs3yKC7+H8RRk3i5Bx2myxvYIFYb3O5bf1PR2fXpGS/5HHrHk/rjLYCCbkqU4H/TnCAvyOBHzBWHR8cMlBFBANsCt59Ccl/zpqFiMWLkiaCEada9Nkl1JWk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
