travis:
  secure:
    BINSTAR_TOKEN: GWgOQ7lo+r0jXKGW5MEtO/xJpF6fvU1oHolcT35AiN8rFHNevmiV41Cyglk1VmZydq05xAebX/xq6plY6yhEkpHUP0YmcDCr1Kt9I5zmIs36v1ZF1IdLqTOU/UcN7SNuJ3ozB0xnKrxh9N3cYEjgUdbMuFkVRanWcXxMpWzKsV39G167RcgwWm82OK0c8ncdGUlk++1xGcFCZFZ7Tj8bS7y6G79g038z7LolS6bRdhdQzZUkoXl5cwhsWnO92LunIrm+FweLHNo0WqwSe0xCANuxfhvb2Dl3anxHFgN/AfOKxeftXdktlSQhXUoj6k0/bnuT71phJjypphDZMouSZ11G02wy3pnb7nXb2SFLk2raYcD/0jR97U02kSmIO61nzrAg07PnEvtiqtKnJZi3CHeyUFS2CrPRh0uk6FFtlq+AFDJK51L68KsJmDV2OfxNcFnmm8he/+Ai0J3rE07UsB9KYydBb+olPuoE4Q1lxvsu1tYBsViwpndwWcEfMTC0lWFg8LDzEDClHfDbb0O8UtRFEGopiB+BWYnpWIWv4OKJspr4QceJZND1u9qDNNeGc6PKREdGL0wyedxi3nLn5Z9JWm0lrikQ8cieq6dvh72a25FgBOU6L0moOSjoTkq1Nl3VsmQJrOovhhmvqRhwX+6iPjcXraojG6KgmWmaU2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
