travis:
  secure:
    BINSTAR_TOKEN: GLJXzfCzu0FT/OWK1zKBMyPnayD3GEJhlKvCz0b/wAmWbY8SIEOqvsvqP8LJIMF50T+tgWSFyOvmQiDF9QLXxDevFXcOW4SA4vyCpCnmYgsrh7fMCuCthpwE23RWbeA8c5Ej9PwMl03/go3uzyq+Z/9gYtOFxbzA2i4poGZ3fgehfSIl4O49qZH9HX0hIl9CAvWf+1aQcZwpapMhYpuOqp8lsKr06wx/lA/IKGNXVvwaAuPUGLPfvFtFr8I3aeUy50vhN/TYTBxsGVHrA/BuJOcZeplUSIjBtCKUZ1p6vXIj9A1dy/AsUdGF+jVYMv+WoQrCO8zqk5UlST7V62c9qOLVSpDqYMPEb7DQTHU1+jmCAaG/0K2o1um1nyHS+FJjElI5hx1jrWBRR2kbf/DRAtrWxwndHZoaSRSHYqLpRaIeLlFThVEfdV0bxTjwNEqyzItclkFfHpxOWBJD8uSL9BTFgexuzKFS3e2LlTaFL9vC6qBIVfVAAJIIxKXWSJ5fYe109m5tZMa8/D6qubfAOZILYmGGN0BnL8idOzfUyjCphgb5dEBHlKmyeyII4tcN4svvLOPqqzGoRzuZLHNEl3QgZ5bXKlmBE2+Knn0l79veK44MKeIQNoPqF9b0qX56PIyd7SHM5GVhHzEPzCb0DoATsaOna9jx2mpkeFgPa8M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
