travis:
  secure:
    BINSTAR_TOKEN: lV2998LrCwmss4AbgSN3Vy+MtAbeFTqB/fnmgKlWjcxByfWU55XT7FEoBgMauwPWjzRB3bhVRjHxj+ENy+qSJysn1/HxRSFnzUuqXYwUm6s+AhCeDEaf0RINldEdTudCWXyfBakf59WUI/4GukGNaxTkT7RtAIJjG+5vNk2djTPHzUDbQjqv2PDqO8uIXdqWYJdYLITuPO+jMGWIAV9RTfIjb2soZP5LY/phpMjt4RAW1X5sJiGJuXENjB7cjQkwB6bxMrRjA1pF38wrMFPQZXr6z/aietQ93puw9rl8ubenorC8iQu0OZsj2EXnbbL0910rQn+HHC8d8vU+rCAKzK0o22tjquB9OEs5Y8IYmxo6KACUq4KHcArsR2l+lZHat+d8vF1e1XMKX88VEoV45zHISevtd7foqXhwo6Pg0oYeR1yJWaj3mTa3lcv+2rwjIDrdW3wWb06SDgOZCW1wjcCaoOG0kPdtIfB7aZRRxwSyXiJLL5HqsJLNF2ocjJLvEsHb8P9/p764XEG/qOux4S3HQEoi/5cFylf15jThzmUfh5yrYyQqEs3yKC7+H8RRk3i5Bx2myxvYIFYb3O5bf1PR2fXpGS/5HHrHk/rjLYCCbkqU4H/TnCAvyOBHzBWHR8cMlBFBANsCt59Ccl/zpqFiMWLkiaCEada9Nkl1JWk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
